// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: PushDataV3MarketWrapper.proto

package wsmarket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushDataV3MarketWrapper struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Channel string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*PushDataV3MarketWrapper_PublicDeals
	//	*PushDataV3MarketWrapper_PublicIncreaseDepths
	//	*PushDataV3MarketWrapper_PublicLimitDepths
	//	*PushDataV3MarketWrapper_PublicSpotKline
	//	*PushDataV3MarketWrapper_PublicBookTickerBatch
	//	*PushDataV3MarketWrapper_PublicIncreaseDepthsBatch
	//	*PushDataV3MarketWrapper_PublicAggreDepths
	//	*PushDataV3MarketWrapper_PublicAggreDeals
	//	*PushDataV3MarketWrapper_PublicAggreBookTicker
	Body          isPushDataV3MarketWrapper_Body `protobuf_oneof:"body"`
	Symbol        *string                        `protobuf:"bytes,3,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	SymbolId      *string                        `protobuf:"bytes,4,opt,name=symbolId,proto3,oneof" json:"symbolId,omitempty"`
	CreateTime    *int64                         `protobuf:"varint,5,opt,name=createTime,proto3,oneof" json:"createTime,omitempty"`
	SendTime      *int64                         `protobuf:"varint,6,opt,name=sendTime,proto3,oneof" json:"sendTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushDataV3MarketWrapper) Reset() {
	*x = PushDataV3MarketWrapper{}
	mi := &file_PushDataV3MarketWrapper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushDataV3MarketWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDataV3MarketWrapper) ProtoMessage() {}

func (x *PushDataV3MarketWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_PushDataV3MarketWrapper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDataV3MarketWrapper.ProtoReflect.Descriptor instead.
func (*PushDataV3MarketWrapper) Descriptor() ([]byte, []int) {
	return file_PushDataV3MarketWrapper_proto_rawDescGZIP(), []int{0}
}

func (x *PushDataV3MarketWrapper) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PushDataV3MarketWrapper) GetBody() isPushDataV3MarketWrapper_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PushDataV3MarketWrapper) GetPublicDeals() *PublicDealsV3Api {
	if x != nil {
		if x, ok := x.Body.(*PushDataV3MarketWrapper_PublicDeals); ok {
			return x.PublicDeals
		}
	}
	return nil
}

func (x *PushDataV3MarketWrapper) GetPublicIncreaseDepths() *PublicIncreaseDepthsV3Api {
	if x != nil {
		if x, ok := x.Body.(*PushDataV3MarketWrapper_PublicIncreaseDepths); ok {
			return x.PublicIncreaseDepths
		}
	}
	return nil
}

func (x *PushDataV3MarketWrapper) GetPublicLimitDepths() *PublicLimitDepthsV3Api {
	if x != nil {
		if x, ok := x.Body.(*PushDataV3MarketWrapper_PublicLimitDepths); ok {
			return x.PublicLimitDepths
		}
	}
	return nil
}

func (x *PushDataV3MarketWrapper) GetPublicSpotKline() *PublicSpotKlineV3Api {
	if x != nil {
		if x, ok := x.Body.(*PushDataV3MarketWrapper_PublicSpotKline); ok {
			return x.PublicSpotKline
		}
	}
	return nil
}

func (x *PushDataV3MarketWrapper) GetPublicBookTickerBatch() *PublicBookTickerBatchV3Api {
	if x != nil {
		if x, ok := x.Body.(*PushDataV3MarketWrapper_PublicBookTickerBatch); ok {
			return x.PublicBookTickerBatch
		}
	}
	return nil
}

func (x *PushDataV3MarketWrapper) GetPublicIncreaseDepthsBatch() *PublicIncreaseDepthsBatchV3Api {
	if x != nil {
		if x, ok := x.Body.(*PushDataV3MarketWrapper_PublicIncreaseDepthsBatch); ok {
			return x.PublicIncreaseDepthsBatch
		}
	}
	return nil
}

func (x *PushDataV3MarketWrapper) GetPublicAggreDepths() *PublicAggreDepthsV3Api {
	if x != nil {
		if x, ok := x.Body.(*PushDataV3MarketWrapper_PublicAggreDepths); ok {
			return x.PublicAggreDepths
		}
	}
	return nil
}

func (x *PushDataV3MarketWrapper) GetPublicAggreDeals() *PublicAggreDealsV3Api {
	if x != nil {
		if x, ok := x.Body.(*PushDataV3MarketWrapper_PublicAggreDeals); ok {
			return x.PublicAggreDeals
		}
	}
	return nil
}

func (x *PushDataV3MarketWrapper) GetPublicAggreBookTicker() *PublicAggreBookTickerV3Api {
	if x != nil {
		if x, ok := x.Body.(*PushDataV3MarketWrapper_PublicAggreBookTicker); ok {
			return x.PublicAggreBookTicker
		}
	}
	return nil
}

func (x *PushDataV3MarketWrapper) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *PushDataV3MarketWrapper) GetSymbolId() string {
	if x != nil && x.SymbolId != nil {
		return *x.SymbolId
	}
	return ""
}

func (x *PushDataV3MarketWrapper) GetCreateTime() int64 {
	if x != nil && x.CreateTime != nil {
		return *x.CreateTime
	}
	return 0
}

func (x *PushDataV3MarketWrapper) GetSendTime() int64 {
	if x != nil && x.SendTime != nil {
		return *x.SendTime
	}
	return 0
}

type isPushDataV3MarketWrapper_Body interface {
	isPushDataV3MarketWrapper_Body()
}

type PushDataV3MarketWrapper_PublicDeals struct {
	PublicDeals *PublicDealsV3Api `protobuf:"bytes,301,opt,name=publicDeals,proto3,oneof"`
}

type PushDataV3MarketWrapper_PublicIncreaseDepths struct {
	PublicIncreaseDepths *PublicIncreaseDepthsV3Api `protobuf:"bytes,302,opt,name=publicIncreaseDepths,proto3,oneof"`
}

type PushDataV3MarketWrapper_PublicLimitDepths struct {
	PublicLimitDepths *PublicLimitDepthsV3Api `protobuf:"bytes,303,opt,name=publicLimitDepths,proto3,oneof"`
}

type PushDataV3MarketWrapper_PublicSpotKline struct {
	PublicSpotKline *PublicSpotKlineV3Api `protobuf:"bytes,308,opt,name=publicSpotKline,proto3,oneof"`
}

type PushDataV3MarketWrapper_PublicBookTickerBatch struct {
	PublicBookTickerBatch *PublicBookTickerBatchV3Api `protobuf:"bytes,311,opt,name=publicBookTickerBatch,proto3,oneof"`
}

type PushDataV3MarketWrapper_PublicIncreaseDepthsBatch struct {
	PublicIncreaseDepthsBatch *PublicIncreaseDepthsBatchV3Api `protobuf:"bytes,312,opt,name=publicIncreaseDepthsBatch,proto3,oneof"`
}

type PushDataV3MarketWrapper_PublicAggreDepths struct {
	PublicAggreDepths *PublicAggreDepthsV3Api `protobuf:"bytes,313,opt,name=publicAggreDepths,proto3,oneof"`
}

type PushDataV3MarketWrapper_PublicAggreDeals struct {
	PublicAggreDeals *PublicAggreDealsV3Api `protobuf:"bytes,314,opt,name=publicAggreDeals,proto3,oneof"`
}

type PushDataV3MarketWrapper_PublicAggreBookTicker struct {
	PublicAggreBookTicker *PublicAggreBookTickerV3Api `protobuf:"bytes,315,opt,name=publicAggreBookTicker,proto3,oneof"`
}

func (*PushDataV3MarketWrapper_PublicDeals) isPushDataV3MarketWrapper_Body() {}

func (*PushDataV3MarketWrapper_PublicIncreaseDepths) isPushDataV3MarketWrapper_Body() {}

func (*PushDataV3MarketWrapper_PublicLimitDepths) isPushDataV3MarketWrapper_Body() {}

func (*PushDataV3MarketWrapper_PublicSpotKline) isPushDataV3MarketWrapper_Body() {}

func (*PushDataV3MarketWrapper_PublicBookTickerBatch) isPushDataV3MarketWrapper_Body() {}

func (*PushDataV3MarketWrapper_PublicIncreaseDepthsBatch) isPushDataV3MarketWrapper_Body() {}

func (*PushDataV3MarketWrapper_PublicAggreDepths) isPushDataV3MarketWrapper_Body() {}

func (*PushDataV3MarketWrapper_PublicAggreDeals) isPushDataV3MarketWrapper_Body() {}

func (*PushDataV3MarketWrapper_PublicAggreBookTicker) isPushDataV3MarketWrapper_Body() {}

var File_PushDataV3MarketWrapper_proto protoreflect.FileDescriptor

const file_PushDataV3MarketWrapper_proto_rawDesc = "" +
	"\n" +
	"\x1dPushDataV3MarketWrapper.proto\x1a\x16PublicDealsV3Api.proto\x1a\x1fPublicIncreaseDepthsV3Api.proto\x1a\x1cPublicLimitDepthsV3Api.proto\x1a\x1aPublicSpotKlineV3Api.proto\x1a PublicBookTickerBatchV3Api.proto\x1a$PublicIncreaseDepthsBatchV3Api.proto\x1a\x1cPublicAggreDepthsV3Api.proto\x1a\x1bPublicAggreDealsV3Api.proto\x1a PublicAggreBookTickerV3Api.proto\"\xab\a\n" +
	"\x17PushDataV3MarketWrapper\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x126\n" +
	"\vpublicDeals\x18\xad\x02 \x01(\v2\x11.PublicDealsV3ApiH\x00R\vpublicDeals\x12Q\n" +
	"\x14publicIncreaseDepths\x18\xae\x02 \x01(\v2\x1a.PublicIncreaseDepthsV3ApiH\x00R\x14publicIncreaseDepths\x12H\n" +
	"\x11publicLimitDepths\x18\xaf\x02 \x01(\v2\x17.PublicLimitDepthsV3ApiH\x00R\x11publicLimitDepths\x12B\n" +
	"\x0fpublicSpotKline\x18\xb4\x02 \x01(\v2\x15.PublicSpotKlineV3ApiH\x00R\x0fpublicSpotKline\x12T\n" +
	"\x15publicBookTickerBatch\x18\xb7\x02 \x01(\v2\x1b.PublicBookTickerBatchV3ApiH\x00R\x15publicBookTickerBatch\x12`\n" +
	"\x19publicIncreaseDepthsBatch\x18\xb8\x02 \x01(\v2\x1f.PublicIncreaseDepthsBatchV3ApiH\x00R\x19publicIncreaseDepthsBatch\x12H\n" +
	"\x11publicAggreDepths\x18\xb9\x02 \x01(\v2\x17.PublicAggreDepthsV3ApiH\x00R\x11publicAggreDepths\x12E\n" +
	"\x10publicAggreDeals\x18\xba\x02 \x01(\v2\x16.PublicAggreDealsV3ApiH\x00R\x10publicAggreDeals\x12T\n" +
	"\x15publicAggreBookTicker\x18\xbb\x02 \x01(\v2\x1b.PublicAggreBookTickerV3ApiH\x00R\x15publicAggreBookTicker\x12\x1b\n" +
	"\x06symbol\x18\x03 \x01(\tH\x01R\x06symbol\x88\x01\x01\x12\x1f\n" +
	"\bsymbolId\x18\x04 \x01(\tH\x02R\bsymbolId\x88\x01\x01\x12#\n" +
	"\n" +
	"createTime\x18\x05 \x01(\x03H\x03R\n" +
	"createTime\x88\x01\x01\x12\x1f\n" +
	"\bsendTime\x18\x06 \x01(\x03H\x04R\bsendTime\x88\x01\x01B\x06\n" +
	"\x04bodyB\t\n" +
	"\a_symbolB\v\n" +
	"\t_symbolIdB\r\n" +
	"\v_createTimeB\v\n" +
	"\t_sendTimeB=Z;github.com/IvanTurko/mexc-sdk-go/spot/wsmarket;wsmarketb\x06proto3"

var (
	file_PushDataV3MarketWrapper_proto_rawDescOnce sync.Once
	file_PushDataV3MarketWrapper_proto_rawDescData []byte
)

func file_PushDataV3MarketWrapper_proto_rawDescGZIP() []byte {
	file_PushDataV3MarketWrapper_proto_rawDescOnce.Do(func() {
		file_PushDataV3MarketWrapper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PushDataV3MarketWrapper_proto_rawDesc), len(file_PushDataV3MarketWrapper_proto_rawDesc)))
	})
	return file_PushDataV3MarketWrapper_proto_rawDescData
}

var file_PushDataV3MarketWrapper_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PushDataV3MarketWrapper_proto_goTypes = []any{
	(*PushDataV3MarketWrapper)(nil),        // 0: PushDataV3MarketWrapper
	(*PublicDealsV3Api)(nil),               // 1: PublicDealsV3Api
	(*PublicIncreaseDepthsV3Api)(nil),      // 2: PublicIncreaseDepthsV3Api
	(*PublicLimitDepthsV3Api)(nil),         // 3: PublicLimitDepthsV3Api
	(*PublicSpotKlineV3Api)(nil),           // 4: PublicSpotKlineV3Api
	(*PublicBookTickerBatchV3Api)(nil),     // 5: PublicBookTickerBatchV3Api
	(*PublicIncreaseDepthsBatchV3Api)(nil), // 6: PublicIncreaseDepthsBatchV3Api
	(*PublicAggreDepthsV3Api)(nil),         // 7: PublicAggreDepthsV3Api
	(*PublicAggreDealsV3Api)(nil),          // 8: PublicAggreDealsV3Api
	(*PublicAggreBookTickerV3Api)(nil),     // 9: PublicAggreBookTickerV3Api
}
var file_PushDataV3MarketWrapper_proto_depIdxs = []int32{
	1, // 0: PushDataV3MarketWrapper.publicDeals:type_name -> PublicDealsV3Api
	2, // 1: PushDataV3MarketWrapper.publicIncreaseDepths:type_name -> PublicIncreaseDepthsV3Api
	3, // 2: PushDataV3MarketWrapper.publicLimitDepths:type_name -> PublicLimitDepthsV3Api
	4, // 3: PushDataV3MarketWrapper.publicSpotKline:type_name -> PublicSpotKlineV3Api
	5, // 4: PushDataV3MarketWrapper.publicBookTickerBatch:type_name -> PublicBookTickerBatchV3Api
	6, // 5: PushDataV3MarketWrapper.publicIncreaseDepthsBatch:type_name -> PublicIncreaseDepthsBatchV3Api
	7, // 6: PushDataV3MarketWrapper.publicAggreDepths:type_name -> PublicAggreDepthsV3Api
	8, // 7: PushDataV3MarketWrapper.publicAggreDeals:type_name -> PublicAggreDealsV3Api
	9, // 8: PushDataV3MarketWrapper.publicAggreBookTicker:type_name -> PublicAggreBookTickerV3Api
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_PushDataV3MarketWrapper_proto_init() }
func file_PushDataV3MarketWrapper_proto_init() {
	if File_PushDataV3MarketWrapper_proto != nil {
		return
	}
	file_PublicDealsV3Api_proto_init()
	file_PublicIncreaseDepthsV3Api_proto_init()
	file_PublicLimitDepthsV3Api_proto_init()
	file_PublicSpotKlineV3Api_proto_init()
	file_PublicBookTickerBatchV3Api_proto_init()
	file_PublicIncreaseDepthsBatchV3Api_proto_init()
	file_PublicAggreDepthsV3Api_proto_init()
	file_PublicAggreDealsV3Api_proto_init()
	file_PublicAggreBookTickerV3Api_proto_init()
	file_PushDataV3MarketWrapper_proto_msgTypes[0].OneofWrappers = []any{
		(*PushDataV3MarketWrapper_PublicDeals)(nil),
		(*PushDataV3MarketWrapper_PublicIncreaseDepths)(nil),
		(*PushDataV3MarketWrapper_PublicLimitDepths)(nil),
		(*PushDataV3MarketWrapper_PublicSpotKline)(nil),
		(*PushDataV3MarketWrapper_PublicBookTickerBatch)(nil),
		(*PushDataV3MarketWrapper_PublicIncreaseDepthsBatch)(nil),
		(*PushDataV3MarketWrapper_PublicAggreDepths)(nil),
		(*PushDataV3MarketWrapper_PublicAggreDeals)(nil),
		(*PushDataV3MarketWrapper_PublicAggreBookTicker)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PushDataV3MarketWrapper_proto_rawDesc), len(file_PushDataV3MarketWrapper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PushDataV3MarketWrapper_proto_goTypes,
		DependencyIndexes: file_PushDataV3MarketWrapper_proto_depIdxs,
		MessageInfos:      file_PushDataV3MarketWrapper_proto_msgTypes,
	}.Build()
	File_PushDataV3MarketWrapper_proto = out.File
	file_PushDataV3MarketWrapper_proto_goTypes = nil
	file_PushDataV3MarketWrapper_proto_depIdxs = nil
}
