// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: PushDataV3UserWrapper.proto

package wsuser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushDataV3UserWrapper struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Channel string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*PushDataV3UserWrapper_PrivateOrders
	//	*PushDataV3UserWrapper_PrivateDeals
	//	*PushDataV3UserWrapper_PrivateAccount
	Body          isPushDataV3UserWrapper_Body `protobuf_oneof:"body"`
	Symbol        *string                      `protobuf:"bytes,3,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	SymbolId      *string                      `protobuf:"bytes,4,opt,name=symbolId,proto3,oneof" json:"symbolId,omitempty"`
	CreateTime    *int64                       `protobuf:"varint,5,opt,name=createTime,proto3,oneof" json:"createTime,omitempty"`
	SendTime      *int64                       `protobuf:"varint,6,opt,name=sendTime,proto3,oneof" json:"sendTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushDataV3UserWrapper) Reset() {
	*x = PushDataV3UserWrapper{}
	mi := &file_PushDataV3UserWrapper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushDataV3UserWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDataV3UserWrapper) ProtoMessage() {}

func (x *PushDataV3UserWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_PushDataV3UserWrapper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDataV3UserWrapper.ProtoReflect.Descriptor instead.
func (*PushDataV3UserWrapper) Descriptor() ([]byte, []int) {
	return file_PushDataV3UserWrapper_proto_rawDescGZIP(), []int{0}
}

func (x *PushDataV3UserWrapper) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PushDataV3UserWrapper) GetBody() isPushDataV3UserWrapper_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PushDataV3UserWrapper) GetPrivateOrders() *PrivateOrdersV3Api {
	if x != nil {
		if x, ok := x.Body.(*PushDataV3UserWrapper_PrivateOrders); ok {
			return x.PrivateOrders
		}
	}
	return nil
}

func (x *PushDataV3UserWrapper) GetPrivateDeals() *PrivateDealsV3Api {
	if x != nil {
		if x, ok := x.Body.(*PushDataV3UserWrapper_PrivateDeals); ok {
			return x.PrivateDeals
		}
	}
	return nil
}

func (x *PushDataV3UserWrapper) GetPrivateAccount() *PrivateAccountV3Api {
	if x != nil {
		if x, ok := x.Body.(*PushDataV3UserWrapper_PrivateAccount); ok {
			return x.PrivateAccount
		}
	}
	return nil
}

func (x *PushDataV3UserWrapper) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *PushDataV3UserWrapper) GetSymbolId() string {
	if x != nil && x.SymbolId != nil {
		return *x.SymbolId
	}
	return ""
}

func (x *PushDataV3UserWrapper) GetCreateTime() int64 {
	if x != nil && x.CreateTime != nil {
		return *x.CreateTime
	}
	return 0
}

func (x *PushDataV3UserWrapper) GetSendTime() int64 {
	if x != nil && x.SendTime != nil {
		return *x.SendTime
	}
	return 0
}

type isPushDataV3UserWrapper_Body interface {
	isPushDataV3UserWrapper_Body()
}

type PushDataV3UserWrapper_PrivateOrders struct {
	PrivateOrders *PrivateOrdersV3Api `protobuf:"bytes,304,opt,name=privateOrders,proto3,oneof"`
}

type PushDataV3UserWrapper_PrivateDeals struct {
	PrivateDeals *PrivateDealsV3Api `protobuf:"bytes,306,opt,name=privateDeals,proto3,oneof"`
}

type PushDataV3UserWrapper_PrivateAccount struct {
	PrivateAccount *PrivateAccountV3Api `protobuf:"bytes,307,opt,name=privateAccount,proto3,oneof"`
}

func (*PushDataV3UserWrapper_PrivateOrders) isPushDataV3UserWrapper_Body() {}

func (*PushDataV3UserWrapper_PrivateDeals) isPushDataV3UserWrapper_Body() {}

func (*PushDataV3UserWrapper_PrivateAccount) isPushDataV3UserWrapper_Body() {}

var File_PushDataV3UserWrapper_proto protoreflect.FileDescriptor

const file_PushDataV3UserWrapper_proto_rawDesc = "" +
	"\n" +
	"\x1bPushDataV3UserWrapper.proto\x1a\x18PrivateOrdersV3Api.proto\x1a\x17PrivateDealsV3Api.proto\x1a\x19PrivateAccountV3Api.proto\"\xab\x03\n" +
	"\x15PushDataV3UserWrapper\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12<\n" +
	"\rprivateOrders\x18\xb0\x02 \x01(\v2\x13.PrivateOrdersV3ApiH\x00R\rprivateOrders\x129\n" +
	"\fprivateDeals\x18\xb2\x02 \x01(\v2\x12.PrivateDealsV3ApiH\x00R\fprivateDeals\x12?\n" +
	"\x0eprivateAccount\x18\xb3\x02 \x01(\v2\x14.PrivateAccountV3ApiH\x00R\x0eprivateAccount\x12\x1b\n" +
	"\x06symbol\x18\x03 \x01(\tH\x01R\x06symbol\x88\x01\x01\x12\x1f\n" +
	"\bsymbolId\x18\x04 \x01(\tH\x02R\bsymbolId\x88\x01\x01\x12#\n" +
	"\n" +
	"createTime\x18\x05 \x01(\x03H\x03R\n" +
	"createTime\x88\x01\x01\x12\x1f\n" +
	"\bsendTime\x18\x06 \x01(\x03H\x04R\bsendTime\x88\x01\x01B\x06\n" +
	"\x04bodyB\t\n" +
	"\a_symbolB\v\n" +
	"\t_symbolIdB\r\n" +
	"\v_createTimeB\v\n" +
	"\t_sendTimeB9Z7github.com/IvanTurko/mexc-sdk-go/spot/wsuser;wsuserb\x06proto3"

var (
	file_PushDataV3UserWrapper_proto_rawDescOnce sync.Once
	file_PushDataV3UserWrapper_proto_rawDescData []byte
)

func file_PushDataV3UserWrapper_proto_rawDescGZIP() []byte {
	file_PushDataV3UserWrapper_proto_rawDescOnce.Do(func() {
		file_PushDataV3UserWrapper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PushDataV3UserWrapper_proto_rawDesc), len(file_PushDataV3UserWrapper_proto_rawDesc)))
	})
	return file_PushDataV3UserWrapper_proto_rawDescData
}

var file_PushDataV3UserWrapper_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PushDataV3UserWrapper_proto_goTypes = []any{
	(*PushDataV3UserWrapper)(nil), // 0: PushDataV3UserWrapper
	(*PrivateOrdersV3Api)(nil),    // 1: PrivateOrdersV3Api
	(*PrivateDealsV3Api)(nil),     // 2: PrivateDealsV3Api
	(*PrivateAccountV3Api)(nil),   // 3: PrivateAccountV3Api
}
var file_PushDataV3UserWrapper_proto_depIdxs = []int32{
	1, // 0: PushDataV3UserWrapper.privateOrders:type_name -> PrivateOrdersV3Api
	2, // 1: PushDataV3UserWrapper.privateDeals:type_name -> PrivateDealsV3Api
	3, // 2: PushDataV3UserWrapper.privateAccount:type_name -> PrivateAccountV3Api
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_PushDataV3UserWrapper_proto_init() }
func file_PushDataV3UserWrapper_proto_init() {
	if File_PushDataV3UserWrapper_proto != nil {
		return
	}
	file_PrivateOrdersV3Api_proto_init()
	file_PrivateDealsV3Api_proto_init()
	file_PrivateAccountV3Api_proto_init()
	file_PushDataV3UserWrapper_proto_msgTypes[0].OneofWrappers = []any{
		(*PushDataV3UserWrapper_PrivateOrders)(nil),
		(*PushDataV3UserWrapper_PrivateDeals)(nil),
		(*PushDataV3UserWrapper_PrivateAccount)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PushDataV3UserWrapper_proto_rawDesc), len(file_PushDataV3UserWrapper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PushDataV3UserWrapper_proto_goTypes,
		DependencyIndexes: file_PushDataV3UserWrapper_proto_depIdxs,
		MessageInfos:      file_PushDataV3UserWrapper_proto_msgTypes,
	}.Build()
	File_PushDataV3UserWrapper_proto = out.File
	file_PushDataV3UserWrapper_proto_goTypes = nil
	file_PushDataV3UserWrapper_proto_depIdxs = nil
}
